// Package openapi embeds the committed OpenAPI document so the running
// server can report its own contract hash (contractSha in GET /api/v1/config,
// 5.10) without touching disk. The file is regenerated by `make openapi`
// (backend/cmd/openapi) and this package only ever reads what was committed
// at build time — it does not participate in generating the spec.
package openapi

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
)

// JSON is the committed spec's raw bytes.
//
//go:embed openapi.json
var JSON []byte

// Sha256Hex is the hex-encoded sha256 of the embedded document, computed
// once at init rather than per-request.
var Sha256Hex = func() string {
	sum := sha256.Sum256(JSON)
	return hex.EncodeToString(sum[:])
}()
